query transactions($owner: String!, $recipient: String!) {
  transactions(
    owners: [$owner]
    recipients: [$recipient]
    tags: [
      { name: "App-Name", values: ["ArVerifyDev"] },
      { name: "Type", values: ["Tip"] },
    ]
  ) {
    edges {
      node {
        quantity {
          ar
        }
      }
    }
  }
}

